# -*- coding: utf-8 -*-
"""05_Random_Forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phPyflthQ1eUP3aBafm_PIwe8eBnvdBO
"""

# RANDOM FOREST CLASSIFIER

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


# Create sample dataset
from sklearn.datasets import load_iris

iris = load_iris()

X = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

y = iris.target

print("Dataset:")
print(X.head())

print("\nShape:", X.shape)


# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining data:", X_train.shape)
print("Testing data:", X_test.shape)


# Random Forest Classifier
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)


# Train the model
rf.fit(X_train, y_train)

print("\nRandom Forest model training completed")


# Prediction
y_pred = rf.predict(X_test)

print("\nPredictions:")
print(y_pred)


# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)


# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)


# Classification Report
print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=iris.target_names
    )
)


# Feature Importance
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print("\nFeature Importance:")
print(importance)


# Feature Importance Plot
plt.figure(figsize=(8, 5))

sns.barplot(
    data=importance,
    x="Importance",
    y="Feature"
)

plt.title("Random Forest Feature Importance")
plt.show()