# -*- coding: utf-8 -*-
"""07_Decision_Tree_Pruning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cdwge7qjaKJR7eIdFMkQkcTjpuZ3q0d
"""

# DECISION TREE - SPLITTING CRITERIA, CCP PRUNING AND DEPTH SWEEP

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


# Load Dataset
iris = load_iris()

X = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

y = iris.target

print("Dataset shape:", X.shape)
print("\nFirst 5 rows:")
print(X.head())


# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTraining data:", X_train.shape)
print("Testing data:", X_test.shape)


# --------------------------------------------------
# 1. DECISION TREE USING GINI INDEX
# --------------------------------------------------

dt_gini = DecisionTreeClassifier(
    criterion="gini",
    random_state=42
)

dt_gini.fit(X_train, y_train)

y_pred_gini = dt_gini.predict(X_test)

accuracy_gini = accuracy_score(
    y_test,
    y_pred_gini
)

print("\nDecision Tree - Gini Index")
print("Accuracy:", accuracy_gini)


# --------------------------------------------------
# 2. DECISION TREE USING ENTROPY
# --------------------------------------------------

dt_entropy = DecisionTreeClassifier(
    criterion="entropy",
    random_state=42
)

dt_entropy.fit(X_train, y_train)

y_pred_entropy = dt_entropy.predict(X_test)

accuracy_entropy = accuracy_score(
    y_test,
    y_pred_entropy
)

print("\nDecision Tree - Entropy")
print("Accuracy:", accuracy_entropy)


# --------------------------------------------------
# 3. CONFUSION MATRIX
# --------------------------------------------------

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_gini))


# --------------------------------------------------
# 4. CLASSIFICATION REPORT
# --------------------------------------------------

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_gini,
        target_names=iris.target_names
    )
)


# --------------------------------------------------
# 5. COST COMPLEXITY PRUNING
# --------------------------------------------------

path = dt_gini.cost_complexity_pruning_path(
    X_train,
    y_train
)

ccp_alphas = path.ccp_alphas

print("\nNumber of CCP Alpha values:", len(ccp_alphas))


# Train trees for different alpha values
trees = []

for alpha in ccp_alphas:
    tree = DecisionTreeClassifier(
        criterion="gini",
        ccp_alpha=alpha,
        random_state=42
    )

    tree.fit(X_train, y_train)

    trees.append(tree)


# Calculate training and testing accuracy
train_scores = [
    tree.score(X_train, y_train)
    for tree in trees
]

test_scores = [
    tree.score(X_test, y_test)
    for tree in trees
]


# Plot CCP pruning results
plt.figure(figsize=(8, 5))

plt.plot(
    ccp_alphas,
    train_scores,
    marker="o",
    label="Training Accuracy"
)

plt.plot(
    ccp_alphas,
    test_scores,
    marker="o",
    label="Testing Accuracy"
)

plt.xlabel("CCP Alpha")
plt.ylabel("Accuracy")
plt.title("Cost Complexity Pruning")
plt.legend()
plt.show()


# --------------------------------------------------
# 6. DEPTH SWEEP
# --------------------------------------------------

depths = range(1, 11)

depth_train_scores = []
depth_test_scores = []


for depth in depths:

    tree = DecisionTreeClassifier(
        criterion="gini",
        max_depth=depth,
        random_state=42
    )

    tree.fit(X_train, y_train)

    depth_train_scores.append(
        tree.score(X_train, y_train)
    )

    depth_test_scores.append(
        tree.score(X_test, y_test)
    )


# Plot depth sweep
plt.figure(figsize=(8, 5))

plt.plot(
    depths,
    depth_train_scores,
    marker="o",
    label="Training Accuracy"
)

plt.plot(
    depths,
    depth_test_scores,
    marker="o",
    label="Testing Accuracy"
)

plt.xlabel("Maximum Tree Depth")
plt.ylabel("Accuracy")
plt.title("Decision Tree Depth Sweep")
plt.legend()
plt.show()


# Best depth
best_depth = depths[
    np.argmax(depth_test_scores)
]

best_accuracy = max(depth_test_scores)

print("\nBest Tree Depth:", best_depth)
print("Best Test Accuracy:", best_accuracy)

print("\nDecision Tree Analysis Completed Successfully")