# -*- coding: utf-8 -*-
"""decision tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9nAkwvzw7urxeqpcXpU4M6H9F-1kpYA
"""

def add(x,y):
  print("Hello")
  return x+y
add(2,4)

for i in range(10):
  print(i)
for j in range(5,0,-1):
  print(j)
 while(i<5):
    print(i)
 i=i+1

for i in range(10):
  print(i)
  print("")
  for j in range(4,0,-2):
    print(j)
    print("")

a=5
b=6
c=7
if(a>b):
  print("a greater")
  elif(b>c):
    print("greater b")
    elif(c>a):
      print("c is greater")
      else:
        print("none")