# -*- coding: utf-8 -*-
"""entropy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5t8pphGHT1JclgJUIHQwsMGZrV69-Kl
"""

y=8.001234567
c='h'
s="hello"
l=[5,5,8.123.'x',"welcome"]