# -*- coding: utf-8 -*-
"""lasso regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16f8mc2ipAfz0-Glfh_YNRJBT36m-c7DD
"""

import pandas as pd
from sklearn.model_selection import train_test_split

# ---------- 1. Load ----------
df = pd.read_csv('kidney_disease.csv')
print("Shape:", df.shape)
print(df.head())

# ---------- 2. Inspect ----------
print("\nDtypes:\n", df.dtypes)
print("\nMissing values:\n", df.isnull().sum())

# ---------- 3. Clean column names and string values ----------
df.columns = df.columns.str.strip()

for col in df.select_dtypes('object').columns:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace('nan', pd.NA)   # str conversion turns real NaNs into "nan" strings, put them back

# ---------- 4. Fix wrongly-typed numeric columns ----------
numeric_like_cols = ['wc', 'rc', 'pcv']  # these come in as text due to stray chars
for col in numeric_like_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# ---------- 5. Drop unnamed index column if present ----------
if 'id' in df.columns:
    df.drop('id', axis=1, inplace=True)

# ---------- 6. Handle missing values ----------
for col in df.columns:
    if df[col].dtype in ['float64', 'int64']:
        df[col] = df[col].fillna(df[col].median())
    else:
        df[col] = df[col].fillna(df[col].mode()[0])

# ---------- 7. Encode categorical/binary columns ----------
binary_maps = {
    'htn': {'yes': 1, 'no': 0},
    'dm': {'yes': 1, 'no': 0},
    'cad': {'yes': 1, 'no': 0},
    'pe': {'yes': 1, 'no': 0},
    'ane': {'yes': 1, 'no': 0},
    'appet': {'good': 1, 'poor': 0},
    'rbc': {'normal': 1, 'abnormal': 0},
    'pc': {'normal': 1, 'abnormal': 0},
    'pcc': {'present': 1, 'notpresent': 0},
    'ba': {'present': 1, 'notpresent': 0},
    'classification': {'ckd': 1, 'notckd': 0, 'ckd\t': 1}  # handles stray tab variants
}

for col, mapping in binary_maps.items():
    if col in df.columns:
        df[col] = df[col].map(mapping)

# catch any leftover unmapped values (e.g. typos) -> fill with mode of that column
for col in binary_maps.keys():
    if col in df.columns and df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

# ---------- 8. Drop duplicates ----------
before = df.shape[0]
df.drop_duplicates(inplace=True)
print(f"\nDropped {before - df.shape[0]} duplicate rows")

# ---------- 9. Final check ----------
print("\nFinal shape:", df.shape)
print("Final dtypes:\n", df.dtypes)
print("Remaining missing values:", df.isnull().sum().sum())

# ---------- 10. Train-test split ----------
X = df.drop('classification', axis=1)
y = df['classification']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("\nTrain shape:", X_train.shape, "Test shape:", X_test.shape)

# ---------- 11. Save cleaned data ----------
df.to_csv('ckd_cleaned.csv', index=False)
print("\nSaved cleaned dataset as ckd_cleaned.csv")

from google.colab import files
files.download('ckd_cleaned.csv')