# -*- coding: utf-8 -*-
"""linear regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2TGYNeqy0LQEhMTjzE_76X0XYGuF0mF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/placement.csv')

df = pd.read_csv('/content/placement.csv')