# -*- coding: utf-8 -*-
"""01_Bivariate_Multivariate_EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_Z4bXE2ikfdRBVuTb6yftGXu0DGNjMY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("placement_predict_50k
.csv")

print(df.head())
print(df.columns)

# BIVARIATE ANALYSIS

# Scatter Plot
plt.figure(figsize=(6,4))
sns.scatterplot(
    data=df,
    x="CGPA",
    y="AttendancePercent"
)
plt.title("CGPA vs Attendance Percentage")
plt.show()


# Regression Plot
plt.figure(figsize=(6,4))
sns.regplot(
    data=df,
    x="CGPA",
    y="CodingTestScore"
)
plt.title("CGPA vs Coding Test Score")
plt.show()


# Box Plot
plt.figure(figsize=(6,4))
sns.boxplot(
    data=df,
    x="PlacementStatus",
    y="CGPA"
)
plt.title("CGPA vs Placement Status")
plt.show()


# Violin Plot
plt.figure(figsize=(6,4))
sns.violinplot(
    data=df,
    x="PlacementStatus",
    y="AttendancePercent"
)
plt.title("Attendance vs Placement Status")
plt.show()


# Gender vs Placement
plt.figure(figsize=(6,4))
sns.countplot(
    data=df,
    x="Gender",
    hue="PlacementStatus"
)
plt.title("Gender vs Placement Status")
plt.show()


# Stream vs Placement
plt.figure(figsize=(10,5))
sns.countplot(
    data=df,
    x="Stream",
    hue="PlacementStatus"
)
plt.xticks(rotation=45)
plt.title("Stream vs Placement Status")
plt.show()

# MULTIVARIATE ANALYSIS

# Correlation Heatmap
plt.figure(figsize=(12,8))

sns.heatmap(
    df.select_dtypes(include=["int64", "float64"]).corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")
plt.show()


# Pair Plot
sns.pairplot(
    df[
        [
            "CGPA",
            "AttendancePercent",
            "CodingTestScore",
            "AptitudeTestScore",
            "PlacementStatus"
        ]
    ],
    hue="PlacementStatus"
)

plt.show()

print("\nEDA Completed Successfully")

