# -*- coding: utf-8 -*-
"""04_Titanic_Logistic_Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWnqSaYtQ0P5nlgeuInX8_KnoF5KekJ_
"""

# TITANIC SURVIVAL - LOGISTIC REGRESSION

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


# Load the dataset
df = pd.read_csv("titanic.csv")


# Understand the dataset
print(df.head())
print("\nShape:", df.shape)
print("\nColumns:")
print(df.columns)

print("\nDataset Information:")
print(df.info())

print("\nDescriptive Statistics:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())


# EDA - Survival Count
sns.countplot(
    x="survived",
    data=df
)

plt.title("Titanic Survival Count")
plt.show()


# Survival by Gender
sns.countplot(
    x="sex",
    hue="survived",
    data=df
)

plt.title("Survival by Gender")
plt.show()


# Survival by Passenger Class
sns.countplot(
    x="pclass",
    hue="survived",
    data=df
)

plt.title("Survival by Passenger Class")
plt.show()


# Select required features
features = [
    "pclass",
    "sex",
    "age",
    "sibsp",
    "parch",
    "fare",
    "embarked"
]

X = df[features].copy()

y = df["survived"]


# Handle missing numerical values
X["age"] = X["age"].fillna(
    X["age"].median()
)


# Handle missing categorical values
X["embarked"] = X["embarked"].fillna(
    X["embarked"].mode()[0]
)


print("\nMissing values after handling:")
print(X.isnull().sum())


# One-hot encoding
X = pd.get_dummies(
    X,
    columns=["sex", "embarked"],
    drop_first=True
)

print("\nEncoded Features:")
print(X.head())


# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# Feature Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)


# Logistic Regression
model = LogisticRegression(
    max_iter=1000
)

model.fit(
    X_train_scaled,
    y_train
)

print("\nModel training completed")


# Prediction
y_pred = model.predict(
    X_test_scaled
)

print("\nFirst 20 predictions:")
print(y_pred[:20])